const tap = require('tap');
const escape = require('./escape');
const sqlstring = require('sqlstring');

tap.equal(escape('Test'), `'Test'`, 'regular string');
tap.equal(escape(`whomst'd've`), `'whomst''d''ve'`, 'postgres custom string escaping');
tap.equal(escape(`now()`), `now()`, 'now() should not be escaped');
tap.equal(escape(`NOW()`), `NOW()`, 'NOW() should not be escaped');
tap.equal(escape(1.32), sqlstring.escape(1.32), 'non-string values should be passed directly to sqlstring');
tap.equal(escape("A \\ A"), `'A \\ A'`, 'should match');
tap.equal(escape(`' OR 1=1 --`), `''' OR 1=1 --'`, 'sql injection 101 should not work');
tap.equal(escape('\fmore text'), `''||E'\\f'||'more text'`, '\\f should be escaped the right way (1)');
tap.equal(escape('more\ftext'), `'more'||E'\\f'||'text'`, '\\f should be escaped the right way (2)');
tap.equal(escape('more text\f'), `'more text'||E'\\f'||''`, '\\f should be escaped the right way (3)');
tap.equal(escape('\nmore text'), `''||E'\\n'||'more text'`, '\\n should be escaped the right way (1)');
tap.equal(escape('more\ntext'), `'more'||E'\\n'||'text'`, '\\n should be escaped the right way (2)');
tap.equal(escape('more text\n'), `'more text'||E'\\n'||''`, '\\n should be escaped the right way (3)');
tap.equal(escape('\rmore text'), `''||E'\\r'||'more text'`, '\\r should be escaped the right way (1)');
tap.equal(escape('more\rtext'), `'more'||E'\\r'||'text'`, '\\r should be escaped the right way (2)');
tap.equal(escape('more text\r'), `'more text'||E'\\r'||''`, '\\r should be escaped the right way (3)');
tap.equal(escape('\tmore text'), `''||E'\\t'||'more text'`, '\\t should be escaped the right way (1)');
tap.equal(escape('more\ttext'), `'more'||E'\\t'||'text'`, '\\t should be escaped the right way (2)');
tap.equal(escape('more text\t'), `'more text'||E'\\t'||''`, '\\t should be escaped the right way (3)');
tap.equal(escape('\vmore text'), `''||E'\\v'||'more text'`, '\\v should be escaped the right way (1)');
tap.equal(escape('more\vtext'), `'more'||E'\\v'||'text'`, '\\v should be escaped the right way (2)');
tap.equal(escape('more text\v'), `'more text'||E'\\v'||''`, '\\v should be escaped the right way (3)');